services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./start-nginx.sh:/start-nginx.sh
    environment:
      - COMPANY_1=${COMPANY_1}
      - COMPANY_2=${COMPANY_2}
    command: /bin/bash -c "chmod +x /start-nginx.sh && /start-nginx.sh"
    restart: always

volumes:
  nginx_ecommerce_data:
