global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'monitoring-prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
      - targets: ['cadvisor:8080']
      - targets: ['localhost:9090']
      - targets: ['pushgateway:9091']

  - job_name: 'company-profile'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.22:9100'
          - '10.128.0.23:9100'
          - '10.128.0.22:8080'
          - '10.128.0.23:8080'

  - job_name: 'database'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.24:9100'
          - '10.128.0.24:8080'

  - job_name: 'ecommerce'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.25:9100'
          - '10.128.0.26:9100'
          - '10.128.0.25:8080'
          - '10.128.0.26:8080'

  - job_name: 'fileserver'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.27:9100'
          - '10.128.0.27:8080'

  - job_name: 'load-balancers'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.28:9100'
          - '10.128.0.29:9100'
          - '10.128.0.28:8080'
          - '10.128.0.29:8080'

  - job_name: 'monitoring-observium'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.31:9100'
          - '10.128.0.31:8080'

  - job_name: 'monitoring-portainer'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.33:9100'
          - '10.128.0.33:8080'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager:9093'
