global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'monitoring-prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
      - targets: ['cadvisor:8080']
      - targets: ['localhost:9090']
      - targets: ['pushgateway:9091']

  - job_name: 'company-profile'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.14:9100'
          - '10.128.0.15:9100'
          - '10.128.0.14:8080'
          - '10.128.0.15:8080'

  - job_name: 'database'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.12:9100'
          - '10.128.0.12:8080'

  - job_name: 'ecommerce'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.16:9100'
          - '10.128.0.17:9100'
          - '10.128.0.16:8080'
          - '10.128.0.17:8080'

  - job_name: 'fileserver'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.18:9100'
          - '10.128.0.18:8080'

  - job_name: 'load-balancers'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.19:9100'
          - '10.128.0.20:9100'
          - '10.128.0.19:8080'
          - '10.128.0.20:8080'

  - job_name: 'monitoring-observium'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.21:9100'

  - job_name: 'monitoring-portainer'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.128.0.21:9100'
          - '10.128.0.21:8080'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
