version: '3.9'

services:
  wordpress_ecommerce:
    image: wordpress:latest
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: 10.128.0.3
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpressecomm
    volumes:
      - wordpress_ecommerce_data:/var/www/html

volumes:
  wordpress_ecommerce_data:

