- name: Install git and clone/pull repository on all instances
  hosts: all
  become: true
  tasks:
    - name: Update all packages using the apt repository
      apt:
        update_cache: yes
      become: true

    - name: Install git
      apt:
        name: git
        state: present
      become: true

    - name: Ensure the destination directory exists
      file:
        path: '/home/apriansyah_syahrul/Mitigas'
        state: directory
        mode: '0755'
      become: true

    - name: Clone or pull the MITI-Configuration-files repository
      git:
        repo: 'https://github.com/SyahrulApr86/MITI-Configuration-files.git'
        dest: '/home/apriansyah_syahrul/Mitigas'
        version: 'HEAD'
        force: yes
      become: true