- name: Run docker compose down and up for LDAP on ldap
  hosts: ldap
  become: true
  tasks:
    - name: Run docker compose down
      command: docker compose down
      args:
        chdir: /home/apriansyah_syahrul/Mitigas/LDAP

    - name: Remove specific Docker volumes
      command: docker volume rm ldap_data_certificates ldap_slapd_database ldap_slapd_config
      ignore_errors: yes
      become: true

    - name: Run docker compose up
      command: docker compose up -d
      args:
        chdir: /home/apriansyah_syahrul/Mitigas/LDAP
