---
- name: Run docker-compose down and up on node_exporter instances
  hosts: node_exporter
  become: true
  tasks:
    - name: Run docker-compose down
      command: docker-compose down
      args:
        chdir: /home/apriansyah_syahrul/Mitigas/Prometheus-Grafana/exporter

    - name: Remove specific Docker volumes
      command: docker volume rm node_exporter_data cadvisor_data
      ignore_errors: true
      become: true

    - name: Run docker-compose up
      command: docker-compose up -d
      args:
        chdir: /home/apriansyah_syahrul/Mitigas/Prometheus-Grafana/exporter
