services:
  wordpress_ecommerce:
    image: wordpress:latest
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: 10.128.0.24
      WORDPRESS_DB_USER: databaseuser
      WORDPRESS_DB_PASSWORD: passworddatabaseuser
      WORDPRESS_DB_NAME: wordpressecomm
    volumes:
      - wordpress_ecommerce_data:/var/www/html

volumes:
  wordpress_ecommerce_data:

