services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_TLS_CRT_FILENAME=${LDAP_TLS_CRT_FILENAME}
      - LDAP_TLS_KEY_FILENAME=${LDAP_TLS_KEY_FILENAME}
      - LDAP_TLS_CA_CRT_FILENAME=${LDAP_TLS_CA_CRT_FILENAME}
      - LDAP_READONLY_USER=${LDAP_READONLY_USER}
      - LDAP_READONLY_USER_USERNAME=${LDAP_READONLY_USER_USERNAME}
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
    networks:
      - openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "8082:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - openldap

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    hostname: keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=dev-file
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
    volumes:
      - ./start-keycloak.sh:/opt/keycloak/bin/start-keycloak.sh
    entrypoint: ["/bin/bash", "/opt/keycloak/bin/start-keycloak.sh"]
    depends_on:
      - openldap
    networks:
      - openldap

networks:
  openldap:
    driver: bridge