version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpass
      MYSQL_USER: databaseuser
      MYSQL_PASSWORD: passworddatabaseuser
      MYSQL_DATABASE: initdb
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

